### PR TITLE
Update yolov10 model

### PR DESCRIPTION
**Pull request by OrangeCellRBX**

### CODE REVIEW

**Comment by OrangeCellRBX** [comment]
just update two model(training with yolov10)

**Comment by YoinkedYoink** [comment]
Can I ask you what yolov10 model this is based off of?

Also have you tested it, just I'm not home and it would make it a bit easier.

**Comment by OrangeCellRBX** [comment]
Yolov10 based yolov8 so the script can running with yolov8.

**Comment by YoinkedYoink** [comment]
No like, is it based off of the small, large, xlarge model?

**Comment by YoinkedYoink** [comment]
Also, can you remove the DS_STORE files. Github doesn't let me for some reason?

**Pull request closed without merging**
